config/routes.rb
Rails.application.routes.draw do


  root   'static_pages#home'
  get    'static_pages/home'
  get    'vocabularies/show'
  get    'vocabularies/new'
  get    'sessions/new'
  get    '/signup',   to: 'users#new'
  post   '/signup',   to: 'users#create'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  get    '/new',      to: 'vocabularies#new'
  post   '/create',   to: 'vocabularies#create'
  get    '/show',     to: 'vocabularies#show'
  resources :users
  resources :vocabularies,         only: [:create, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :vocabularies, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum:255 }, 
  format:{ with:VALID_EMAIL_REGEX },
  uniqueness: { case_sensitive:false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/models/vocabulary.rb
class Vocabulary < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :word, presence: true, length: { maximum: 50 }
  validates :meaning, presence: true, length: { maximum: 300 }
  validates :similarity, length: { maximum: 300 }
  validates :example, length: { maximum: 500 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])

    if params[:q] && params[:q].reject { |key, value| value.blank? }.present?
      @q = @user.vocabularies.ransack(vocabularies_search_params)
      @vocabularies = @q.result.paginate(page: params[:page])
    else
      @q = Vocabulary.none.ransack
      @vocabularies = @user.vocabularies.paginate(page: params[:page])
    end
    @url = user_path(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Soword!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def vocabularies_search_params
    params.require(:q).permit(:word_or_similarity_cont)
  end
end

app/controllers/vocabularies_controller.rb
class VocabulariesController < ApplicationController

  before_action :correct_user, only: [:show, :destroy]

  def show
  end

  def new
    @vocabulary = Vocabulary.new
  end

  def create
    @vocabulary = current_user.vocabularies.build(vocabulary_params)
    if @vocabulary.save
      redirect_to current_user
    else
      @q = Vocabulary.none.ransack
      @feed_items = current_user.feed.paginate(page: params[:page])
      render 'new'
    end
  end

  def destroy
    @vocabulary.destroy
    flash[:success] = "Vocabulary deleted"
    redirect_to request.referrer || root_url
  end

  def vocabulary_params
    params.require(:vocabulary).permit(:word, :meaning, :similarity, :example)
  end

  def correct_user
    @vocabulary = current_user.vocabularies.find_by(id: params[:id])
    redirect_to root_url if @vocabulary.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/vocabularies_helper.rb
module VocabulariesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-light bg-light">
  <div class="container">
    <%= link_to "SOWORD", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "ホーム",   root_path %></li>
      <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "My単語帳", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class = "container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_vocabularies_search_form.html.erb
<%= search_form_for @q, url: @url do |f| %>
  <%= f.label :word_or_similarity_cont, '検索' %>
  <div class="input-group">
    <%= f.text_field :word_or_similarity_cont, placeholder: "単語・類似", class: 'form-control' %>
    <span class="input-group-btn">
     <%= f.submit '検索', class: "btn btn-primary" %>
    </span>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div>
  <h1>Sowordで自分だけの単語帳を作ろう</h1>
  <br><h4>＜使い方＞</h2>
  <br><h4>・「新規登録」でアカウント作成</h4>
  <br><h4>・My単語帳に新しく覚えた単語をどんどん追加！</h4>
  <br><h4>・普段の何気ない会話で出てきた単語をメモ</h4>
  <br><h4>・類似した単語でも検索できる</h4>
  <br><h4>・完璧に覚えた単語は削除しても良し</h4>
  <%= link_to "新規登録", signup_path, class: "btn btn-success" %>
</div>

app/views/users/new.html.erb
<% provide(:title, '新規登録') %>
<h1>新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label '名前' %>
      <%= f.text_field :name, class: 'form_control' %>

      <%= f.label 'Eメール' %>
      <%= f.email_field :email, class: 'form_control' %>

      <%= f.label 'パスワード' %>
      <%= f.password_field :password, class: 'form_control' %>

      <%= f.label 'パスワード確認', "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form_control' %>

      <%= f.submit "アカウント登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class = "row">
  <aside class = "col-md-4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
    <div class="col-md-8">
      
        <div class="row">
          <div class="col-md-4">
            <h3>単語</h3>
          </div>
          <div class="search_form">
            <%= render 'shared/vocabularies_search_form' %>
          </div>
        </div>
        <%= link_to "登録", new_path, class: "btn btn-success" %>
        <% if @user.vocabularies.any? %>
        <ol class="vocabularies">
          <%= render @vocabularies %>
        </ol>
        <%= will_paginate @vocabularies %>
      <% end %>
    </div>
</div>

app/views/vocabularies/_error_messages.html.erb
<% if @vocabulary.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@vocabulary.errors.count, "error") %>.
    </div>
    <ul>
    <% @vocabulary.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/vocabularies/_vocabulary.html.erb
<li id="vocabulary-<%= vocabulary.id %>">
  <div class="card border-secondary mb-3" style="max-width: 80rem;">
    <div class="card-header">
      <h4>
        <span class="word"><%= vocabulary.word %></span>
        &nbsp;&nbsp;<span class="meaning"><%= vocabulary.meaning %></span>
      </h4>
    </div>
  </div>
  <div class="card-body text-secondary">
    <p class="card-text">
      <h5>
        <br>類似：
        <span class="similarity"><%= vocabulary.similarity %></span>
        <br>例文：
        <span class="example"><%= vocabulary.example %></span>
        <br><br><%= link_to "削除", vocabulary, method: :delete, data: { confirm: "単語を削除しますか？" } %>
      </h5>
    </p>
  </div>
</li>

app/views/vocabularies/edit.html.erb
<% provide(:title, "Edit") %>
<h1>Update word</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@vocabulary, url: edit_vocabulary_path(params[:id])) do |f| %>
      <%= render 'vocabularies/error_messages' %>

      <%= f.label :word %>
      <%= f.text_field :word, class: 'form-control' %>

      <%= f.label :meaning %>
      <%= f.text_field :meaning, class: 'form-control' %>

      <%= f.label :similarity %>
      <%= f.text_field :similarity, class: 'form-control' %>

      <%= f.label :example %>
      <%= f.text_field :example, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/vocabularies/new.html.erb
<% provide(:title, '単語登録') %>
<h1>単語登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@vocabulary, url: create_path) do |f| %>
    <%= render 'vocabularies/error_messages' %>

      <%= f.label '単語' %>
      <%= f.text_field :word, class: 'form_control' %>

      <%= f.label '意味' %>
      <%= f.text_field :meaning, class: 'form_control' %>

      <%= f.label '類似' %>
      <%= f.text_field :similarity, class: 'form_control' %>

      <%= f.label '例文' %>
      <%= f.text_field :example, class: 'form_control' %>

      <%= f.submit "単語登録", class: "btn btn-primary" %>
    <% end %>
    <%= link_to "My単語帳へ戻る", current_user %>
  </div>
</div>